import { useState, useEffect } from 'react';
import { Phone, PhoneIncoming, Clock, CheckCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import CallVolumeChart from '../CallVolumeChart';

/**
 * Provider dashboard tab: call analytics showing GlowBuddy-generated calls.
 */
export default function CallAnalyticsTab({ providerId }) {
  const [callLogs, setCallLogs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!providerId) return;
    fetchCalls();
  }, [providerId]);

  async function fetchCalls() {
    setLoading(true);
    const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const { data } = await supabase
      .from('call_logs')
      .select('*')
      .eq('provider_id', providerId)
      .gte('called_at', thirtyDaysAgo)
      .order('called_at', { ascending: false });
    setCallLogs(data || []);
    setLoading(false);
  }

  const totalCalls = callLogs.length;
  const completedCalls = callLogs.filter(c => c.status === 'completed').length;
  const answerRate = totalCalls > 0 ? Math.round((completedCalls / totalCalls) * 100) : 0;
  const avgDuration = completedCalls > 0
    ? Math.round(
        callLogs
          .filter(c => c.status === 'completed' && c.duration_seconds)
          .reduce((sum, c) => sum + c.duration_seconds, 0) /
        Math.max(callLogs.filter(c => c.status === 'completed' && c.duration_seconds).length, 1)
      )
    : 0;

  // Group by week for chart
  const weeklyData = (() => {
    const weeks = {};
    const now = new Date();
    for (let i = 3; i >= 0; i--) {
      const start = new Date(now.getTime() - (i + 1) * 7 * 24 * 60 * 60 * 1000);
      const end = new Date(now.getTime() - i * 7 * 24 * 60 * 60 * 1000);
      const label = `Week ${4 - i}`;
      weeks[label] = { label, calls: 0, start, end };
    }
    for (const call of callLogs) {
      const callDate = new Date(call.called_at);
      for (const week of Object.values(weeks)) {
        if (callDate >= week.start && callDate < week.end) {
          week.calls++;
          break;
        }
      }
    }
    return Object.values(weeks).map(({ label, calls }) => ({ label, calls }));
  })();

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12 text-text-secondary">
        Loading call analytics...
      </div>
    );
  }

  return (
    <div>
      <div className="mb-6">
        <h2 className="text-lg font-bold text-text-primary mb-1">Calls Generated by GlowBuddy</h2>
        <p className="text-sm text-text-secondary">
          Calls from patients who found you on GlowBuddy this month.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
        <div className="glow-card p-4 text-center">
          <PhoneIncoming size={20} className="mx-auto mb-2 text-rose-accent" />
          <p className="text-2xl font-bold text-text-primary">{totalCalls}</p>
          <p className="text-xs text-text-secondary">Total Calls</p>
        </div>
        <div className="glow-card p-4 text-center">
          <CheckCircle size={20} className="mx-auto mb-2 text-green-500" />
          <p className="text-2xl font-bold text-text-primary">{answerRate}%</p>
          <p className="text-xs text-text-secondary">Answer Rate</p>
        </div>
        <div className="glow-card p-4 text-center">
          <Clock size={20} className="mx-auto mb-2 text-blue-500" />
          <p className="text-2xl font-bold text-text-primary">
            {avgDuration > 60 ? `${Math.floor(avgDuration / 60)}m ${avgDuration % 60}s` : `${avgDuration}s`}
          </p>
          <p className="text-xs text-text-secondary">Avg Duration</p>
        </div>
        <div className="glow-card p-4 text-center">
          <Phone size={20} className="mx-auto mb-2 text-amber-500" />
          <p className="text-2xl font-bold text-text-primary">{completedCalls}</p>
          <p className="text-xs text-text-secondary">Completed</p>
        </div>
      </div>

      {/* Chart */}
      <div className="glow-card p-6 mb-6">
        <h3 className="text-sm font-semibold text-text-primary mb-4">Calls by Week</h3>
        <CallVolumeChart data={weeklyData} chart="bar" />
      </div>

      {totalCalls === 0 && (
        <div className="text-center py-8 text-text-secondary">
          <Phone size={32} className="mx-auto mb-3 opacity-40" />
          <p className="text-sm">No calls recorded yet. Once patients start calling through GlowBuddy, you'll see your analytics here.</p>
        </div>
      )}
    </div>
  );
}
